AWSTemplateFormatVersion: "2010-09-09"
Description: SageMaker Batalha - CloudFormation Template

Parameters:
  EnvironmentName:
    Description: An environment name that is prefixed to resource names
    Type: String
    AllowedValues: 
      - HackaA
      - HackaB
    Default: HackaA
    ConstraintDescription: 'Invalid Environment Name! Allowed values: HackaA, HackaB'

Resources:
  NotebookInstance:
    Type: "AWS::SageMaker::NotebookInstance"
    Properties:
      InstanceType: "ml.m5.2xlarge"
      RoleArn: !Sub 'arn:aws:iam::${AWS::AccountId}:role/role-sgmk-batalha-${EnvironmentName}'
      VolumeSizeInGB: 100
      Tags:
        - Key: Name
          Value: "sagemakerbatalha"
        - Key: "Team"
          Value: !Ref 'EnvironmentName'
